```{r, output=FALSE}
library(tidyverse)
```

```{r, output=FALSE}
games <- read_csv("scores.csv")
wv_games <- games |> filter(home_team_state == 'WV', visiting_team_state == 'WV')
```

## Calculate the average differential by year for WV games

```{r}
wv_by_year <- wv_games |> 
  group_by(year) |> 
  summarise(
    min_diff = min(differential),
    max_diff = max(differential),
    avg_diff = mean(differential),
    median_diff = median(differential)
  )
```


## Make a bar chart of average differential

```{r}
ggplot() + 
  geom_bar(data=wv_by_year, aes(x=year, weight=avg_diff)) +
  labs(
    title="Pulling away", 
    subtitle = "Average margin of victory is more than 30 points this season",
    x="Year", 
    y="Average Difference"
) + theme_minimal()
```

## Are there more 35+ margin games?

```{r}
all_games <- wv_games |> 
  group_by(year) |> 
  summarise(all_games = n())

thirtyfive_plus <- wv_games |> 
  filter(differential >= 35) |> 
  group_by(year) |> 
  summarise(thirtyfive_plus_games = n())

thirtyfive_with_pct <- all_games |> 
  inner_join(thirtyfive_plus) |> 
  mutate(pct = thirtyfive_plus_games/all_games *100) |> 
  arrange(desc(pct))

all_games |> 
  inner_join(thirtyfive_plus) |> 
  mutate(pct = thirtyfive_plus_games/all_games *100) |> 
  arrange(desc(pct))
```
```{r}
ggplot() + 
  geom_bar(data=thirtyfive_with_pct, aes(x=year, weight=pct)) +
  labs(
    title="West Virginia High School Football's Lopsided Games", 
    subtitle = "More than 45 percent of games this season have a margin of 35 or more points, a modern high.",
    x="Year", 
    y="Percent"
) + theme_minimal()
```


